name: Publish API documentation to Redocly

on:
  push:
    branches:
      - main

jobs:
  publish-api-docs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          npm install redoc-cli
          npm install -g redoc-cli

      - name: Build and publish API documentation
        env:
          REDOCLY_API_KEY: ${{ secrets.TEST_API_KEY }}
          REPO_NAME: "shereengrg/Redocly"
        run: |
          redoc-cli bundle openapi.yaml -o index.html --template redoc --options.hideDownloadButton=true
          curl -H "Content-Type: text/html" -H "Authorization: ApiKey $TEST_API_KEY" -X PUT https://api.redoc.ly/v2/streams/github/$REPO_NAME/versions/latest/content -d @index.html
